- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-0a3bb5a6589ebd361
    zone_id: "Z0292208N1Q9H7WGUJ5M"
    domain_name: "kalakoti.fun"
    insatnce: 
    - mongodb
  tasks:
  - name: create ec2 insatnce
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output
  
  - name: print the ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"
      

