- name: setup monogdb.server
  hosts: mongodb
  become:yes
  tasks: 
  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: install mongodb-org
    ansible.builtin.package:
      name: mongodb-org
      state: present
  
  - name: allowig all ports
    ansible.builtin.replace:
      path: /etc/mongodb.conf
      regexp: 127.0.0.1
      replace: 0.0.0.0

  - name: start and enable mongodb
    ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes